FROM openjdk:17
EXPOSE 8484
COPY target/StudentRecordManagementSystem-0.0.1-SNAPSHOT.war StudentRecordManagementSystem-0.0.1-SNAPSHOT.war
ENTRYPOINT ["java","-jar","/StudentRecordManagementSystem-0.0.1-SNAPSHOT.war"]
